services:
  github-actions-pipeline:
    container_name: github-action-pipeline
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/employee-service-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

  postgres:
    image: postgres:latest
    container_name: github-action-pipeline-db
    environment:
      POSTGRES_DB: employee-service-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - pipelinedata:/var/lib/postgresql/data

volumes:
  pipelinedata: