on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write
  actions: read
  checks: write

jobs:
  dast-scan:
    name: DAST Scan
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Clear Gradle cache
        run: rm -rf $HOME/.gradle/caches/

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build -x test

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      
      - name: Run application in container to scan with ZAP
        run: |
          docker rm -f github-action-pipeline github-action-pipeline-db || true
          docker-compose up
        # docker run -d -p 8080:9090 --name github-action-pipeline vaibhavshejol/github-actions-pipeline:latest

      - name: Wait 15 seconds to start application
        run: sleep 15

      - name: Application container logs
        run: docker logs github-action-pipeline

      - name: Test container is running
        run: curl -s localhost:9090/com.amazingcode.in/api/message
     
      - name: Run ZAP OWASP full scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          target: 'http://localhost:9090'
          cmd_options: '-a -j -l WARN -r report_html.html -w report_md.md -J report_json.json -z "-addoninstallall" '
          allow_issue_writing: true

      - name: Upload html report
        uses: actions/upload-artifact@v3
        with:
          name: DAST_Report.html
          path: ./report_html.html

      - name: stop docker
        if: always()
        run: |
          docker-compose down
          docker stop github-action-pipeline && docker rm github-action-pipeline && docker container prune --force && docker image prune --force