
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write
  actions: read
  checks: write
  packages: write

jobs:
  dockerization:
    name: Dockerization
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'microsoft'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 
      with:
        gradle-version: 8.5

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      
    - name: Build with Gradle Wrapper
      run: ./gradlew build -x test
      
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        registry: ghcr.io
        image: ${{ github.event.repository.name }}
        tags: latest
        dockerfile: Dockerfile
        username: ${{ github.actor }}
        password: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        
